---
title: "HW4"
author: "Elaine Schaft"
date: "2026-03-05"
output:
  html_document:
    toc: TRUE
    toc_float: TRUE
    number_sections: TRUE
    code_download: TRUE
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## check robots.txt

```{r}
robotstxt::paths_allowed(paths = "https://miamioh.edu/fsb/directory/?up=/query/all/all/Accountancy/all")

robotstxt::paths_allowed(paths = "https://miamioh.edu/fsb/directory/?up=/query/all/all/Economics/all")

robotstxt::paths_allowed(paths = "https://miamioh.edu/fsb/directory/?up=/query/all/all/Entrepreneurship/all")

robotstxt::paths_allowed(paths = "https://miamioh.edu/fsb/directory/?up=/query/all/all/Finance/all")

robotstxt::paths_allowed(paths = "https://miamioh.edu/fsb/directory/?up=/query/all/all/Information%20Systems%20--%20Analytics/all")

robotstxt::paths_allowed(paths = "https://miamioh.edu/fsb/directory/?up=/query/all/all/Marketing/all")

robotstxt::paths_allowed(paths = "https://miamioh.edu/fsb/directory/?up=/query/all/all/Management/all")
```

## Web Scraping

```{r}
fsb_urls = c("https://miamioh.edu/fsb/directory/?up=/query/all/all/Economics/all",
             "https://miamioh.edu/fsb/directory/?up=/query/all/all/Accountancy/all", 
             "https://miamioh.edu/fsb/directory/?up=/query/all/all/Entrepreneurship/all", 
             "https://miamioh.edu/fsb/directory/?up=/query/all/all/Finance/all", 
             "https://miamioh.edu/fsb/directory/?up=/query/all/all/Information%20Systems%20--%20Analytics/all", 
             "https://miamioh.edu/fsb/directory/?up=/query/all/all/Marketing/all", 
             "https://miamioh.edu/fsb/directory/?up=/query/all/all/Management/all")

fsb_tidy = data.frame()
for (fsb_url in fsb_urls) {
  print(fsb_url)
  
fsb_directory = rvest::read_html(fsb_url)

fsb_directory |>
  rvest::html_elements("tr > td:nth-child(1)") |> 
  rvest::html_text2() -> dept_name

fsb_directory |> 
  rvest::html_elements("tr > td:nth-child(3) > strong > a") |> 
  rvest::html_text2() -> fac_name

fsb_directory |> 
  rvest::html_elements("tr > td:nth-child(3) > i") |> 
  rvest::html_text2() -> fac_position

fsb_directory |> 
  rvest::html_elements("tr > td:nth-child(3) > strong > a") |> 
  rvest::html_attr("href") -> fac_webpage

df = data.frame(dept_name, fac_name, fac_position, fac_webpage)

fsb_tidy = rbind(fsb_tidy, df)
print(nrow(fsb_tidy))
}

head(fsb_tidy)
```


